[tool.poetry]
name = "parse-1c-build"
version = "5.14.2"
description = "Parse and build utilities for 1C:Enterprise"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cujoko/parse-1c-build"
keywords = ["1c", "parse", "build", "v8reader", "v8unpack", "gcomp"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
p1cb = "parse_1c_build.__main__:run"

[tool.poetry.dependencies]
python = "^3.9"
cjk-commons = "*"
commons-1c = "*"
loguru = "*"

[tool.poetry.dev-dependencies]
pylint = "*"
pytest = "*"
rope = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
